### ISSUE TITLE
Add Support for VuePress Next v2.0

### ISSUE THREAD

**Issue by ramesh-dada** [meilisearch/vuepress-plugin-meilisearch#175]
Hello I am new in meilisearch I was using algolia before but now planned to use this but it's not yet supported with latest version of vuepress, also it will be great If dark mode also works with vuepress global toggle dark mode introduced in 2.0

**Comment by bidoubiwa** [comment]
Hello @ramesh-dada thanks for raising this issue! 
Since vuepress v2 is still in beta we will probably wait until it is released completely. In v1 there is no global toggle so I'm not sure we could make it work :(

**Comment by Smart-Chou** [comment]
Hi, thank you for creating such a great work. I use it in some documents. I am using vuepress@next version. But the latest version of the plugin is not compatible with vuepress V2.0, can it be supported?

**Comment by bidoubiwa** [comment]
Hello @hyp530 ! We will consider the migration when vuepress v2 gets out of beta :)

**Comment by hyp530** [comment]
> Hello @hyp530 ! We will consider the migration when vuepress v2 gets out of beta :)

They are almost there to get out of beta.  Algolia was integrated into vuepress v2. So it would be great if you could do the migration.

**Comment by bidoubiwa** [comment]
Hello @hyp530 
I took a closer interest on how hard the migration would be, 
based on the migration guide for [plugins authors](https://v2.vuepress.vuejs.org/guide/migration.html#for-plugin-authors), and the [migration guide for plugin API](https://v2.vuepress.vuejs.org/guide/migration.html#plugin-api-change)

This is what came out of it: 

- ✅ API changes: none concern us (at first sight at least)
- ❌ You cannot use other plugins in your plugin anymore, which avoids lots of potential issues caused by plugin nesting. If your plugin depends on other plugins, you should list them in the docs.
- ✅ Most of the v1 hooks have equivalents in v2. The only exception is extendsCli, which has been removed.
- ✅ Webpack related hooks are removed, because VuePress Core has decoupled with webpack. If you still want to modify webpack config in plugin, try modifying app.options.bundlerConfig directly.


Only the second bullet point concerns us as we use [`docs-searchbar.js`](https://github.com/meilisearch/docs-searchbar.js/). If this is an easy fix, than the migration should be an easy task. 

The only thing left that we need to decide is how to handle the versioning of this package. The current `latest` tag is compatible with vuepress v1. We will have to create another npm tag called `next`. 
The issue we have with this is that we'r bound to have two concurrent versioning in github with some impacting vuepress v1 and some vuepress v2. 

Exemple: 
release v0.12.1 : published on `latest`, impact vuepress v1
release v0.13.0 : published on `next`, impact vuepress v2
release v0.14.0 : published on `latest`, impact vuepress v1

etc...

This might be a temporary fix, or maybe we should consider creating a second repo. 

Anyway! Contributors are of course free to help if they want this feature to be implemented faster :)
