### ISSUE TITLE
Internationalization 

### ISSUE THREAD

**Issue by 1ceb3rg** [meilisearch/vuepress-plugin-meilisearch#35]
Hi I'm working on a vuepress page with multiple languages. We're using these settings https://vuepress.vuejs.org/guide/i18n.html. Should I use multiple meili indexes, and is there a way to configure this with this plugin? Thanks

**Comment by curquiza** [comment]
Hello, sorry for the delay @1ceb3rg!
The plugin does not handle internalization yet! But this is clearly the next big feature to implement here. I let the issue open then.

Unfortunately, create multiple indexes would not work with this plugin since you fill only one index UID in the config file.
We will handle it thanks to the facets.

Sorry not to provide a temporary solution here, but be sure this feature will be done in the future!

**Comment by bidoubiwa** [comment]
As per the new policy introduced with the deprecation, we only accept issues raising bugs.
For this reason, I'm closing the issue.
